export const GET_PRODUCT_CATEGORY_LIST = 'GET_PRODUCT_CATEGORY_LIST';
export const GET_SERVICE_CATEGORY_LIST = 'GET_SERVICE_CATEGORY_LIST';
export const GET_PRODUCT_SUBCATEGORY_LIST = 'GET_PRODUCT_SUBCATEGORY_LIST';
export const GET_SERVICE_SUBCATEGORY_LIST = 'GET_SERVICE_SUBCATEGORY_LIST';